export const response = {
    data: [
      {
        id: 1,
        name: "Test Whatsapp",
        region: "US",
        createdOn: 1908828776000,
        price: "Price info of Test Whatsapp",
        csv: "Some CSV link for Whatsapp",
        report: "Some report link for Whatsapp",
        image_url: "Some image url of the campaign",
      },
      {
        id: 2,
        name: "Super Jewels Quest",
        region: "CA, FR",
        createdOn: 1908828786000,
        price: "Price info of Super Jewels Quest",
        csv: "Some CSV link for Super Jewels Quest",
        report: "Some report link for Super Jewels Ques",
        image_url: "Some image url of the campaign",
      },
      {
        id: 3,
        name: "Mole Slayer",
        region: "FR",
        createdOn: 1559806711124,
        price: "Price info of Mole Slayer",
        csv: "Some CSV link for Mole Slayer",
        report: "Some report link for Mole Slayer",
        image_url: "Some image url of the campaign",
      },
      {
        id: 4,
        name: "Mancala Mix",
        region: "JP",
        createdOn: 1559806686574,
        price: "Price info of Mancala Mix",
        csv: "Some CSV link for Mancala Mix",
        report: "Some report link for Mancala Mix",
        image_url: "Some image url of the campaign",
      },
      {
        id: 5,
        name: "Mancala Mix",
        region: "JP",
        createdOn: 1607538600000,
        price: "Price info of Mancala Mix",
        csv: "Some CSV link for Mancala Mix",
        report: "Some report link for Mancala Mix",
        image_url: "Some image url of the campaign",
      },
      {
        id: 6,
        name: "Mancala Mix",
        region: "JP",
        createdOn: 1607797800000,
        price: "Price info of Mancala Mix",
        csv: "Some CSV link for Mancala Mix",
        report: "Some report link for Mancala Mix",
        image_url: "Some image url of the campaign",
      },
      {
        id: 7,
        name: "Mancala Mix",
        region: "JP",
        createdOn: 1608143400000,
        price: "Price info of Mancala Mix",
        csv: "Some CSV link for Mancala Mix",
        report: "Some report link for Mancala Mix",
        image_url: "Some image url of the campaign",
      },
      {
        id: 8,
        name: "Mancala Mix",
        region: "JP",
        createdOn: 1607297345576,
        price: "Price info of Mancala Mix",
        csv: "Some CSV link for Mancala Mix",
        report: "Some report link for Mancala Mix",
        image_url: "Some image url of the campaign",
      },
      {
        id: 9,
        name: "Mancala Mix",
        region: "JP",
        createdOn: 1607297345576,
        price: "Price info of Mancala Mix",
        csv: "Some CSV link for Mancala Mix",
        report: "Some report link for Mancala Mix",
        image_url: "Some image url of the campaign",
      },
      {
        id: 10,
        name: "Mancala Mix",
        region: "JP",
        createdOn: 1597257000000,
        price: "Price info of Mancala Mix",
        csv: "Some CSV link for Mancala Mix",
        report: "Some report link for Mancala Mix",
        image_url: "Some image url of the campaign",
      },
      {
        id: 11,
        name: "Mancala Mix",
        region: "JP",
        createdOn: 1602527400000,
        price: "Price info of Mancala Mix",
        csv: "Some CSV link for Mancala Mix",
        report: "Some report link for Mancala Mix",
        image_url: "Some image url of the campaign",
      },
    ],
  }
  